name: Quality Checks

on:
  workflow_call:

permissions:
  pull-requests: write
  contents: read

jobs:
  lint:
    name: Format, Vet & Lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/notipswe/notip-go-dev:v0.0.1
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Cache Go modules
        uses: actions/cache@v5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-mod-${{ runner.os }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-mod-${{ runner.os }}-

      - name: Download dependencies
        run: go mod download

      - name: gofmt check
        run: test -z "$(gofmt -l .)"

      - name: go vet
        run: go vet ./...

      - name: golangci-lint
        run: golangci-lint run

  test:
    name: Tests & Coverage
    needs: [lint]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/notipswe/notip-go-dev:v0.0.1
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Cache Go modules
        uses: actions/cache@v5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-mod-${{ runner.os }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-mod-${{ runner.os }}-

      - name: Download dependencies
        run: go mod download

      - name: Run tests with coverage
        run: go test -race -coverprofile=coverage.out ./...

      - name: SonarCloud Scan
        run: |
          command -v sonar-scanner
          sonar-scanner -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
